apiVersion: v1
kind: Service
metadata:
  name: edison-python-service
  labels:
    app: edison
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: edison
